# docker-compose.production.yml
version: '3'

volumes:
  taski_pg_data_production:
  taski_static_volume:

# Всё отличие — заменяем build на image и указываем, какой образ использовать
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - taski_pg_data_production:/var/lib/postgresql/data
  backend:
    image: deniv/taski_backend
    env_file: .env
    volumes:
      - taski_static_volume:/backend_static
    depends_on:
      - db
  frontend:
    image: deniv/taski_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - taski_static_volume:/frontend_static
  gateway:
    image: deniv/taski_gateway  # Качаем с Docker Hub
    env_file: .env
    volumes:
      - taski_static_volume:/staticfiles/
    ports:
      - 8000:80
    depends_on:
      - db

